# Generated by Django 3.0.8 on 2020-08-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERIAL_NO', models.IntegerField()),
                ('MOVIES_NAME', models.CharField(max_length=100)),
                ('MOVIES_TYPE', models.CharField(max_length=100)),
                ('MOVIES_LANGUAGE', models.CharField(max_length=100)),
                ('MOVIES_REGION', models.CharField(max_length=100)),
                ('RATINGS', models.DecimalField(decimal_places=2, max_digits=4)),
                ('LINKS', models.CharField(max_length=500)),
            ],
        ),
    ]
